version: 2
jobs:
  build:
    name: Build
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v5-dependencies-{{ checksum "package.json" }}
          - v5-dependencies

      - run: sudo npm install -g @syncano/cli
      - run: npm install

      - save_cache:
        paths:
          - node_modules
        key: v5-dependencies-{{ checksum "package.json" }}

      - save_cache:
          key: v5-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/repo

workflows:
  version: 2
  build-test:
    jobs:
      - build
